title: CBR+PNK
description: A Forged in the Dark game of cyberpunk action
theme: just-the-docs

url: https://thecabinetofcuriosities.github.io/cbrpnk/

twitter_username: emanoelmelo

permalink: pretty

collections:
  en:
    permalink: "/:collection/:path/"
    output: true
# ptbr:
#    permalink: "/:collection/:path/"
#    output: true

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/cbrpnk_logo.png"

aux_links:
  "The Cabinet of Curiosities":
    - https://cabinetofcuriosities.games

# External navigation links
# nav_external_links:
#   - title: The Cabinet of Curiosities
#     url: https://cabinetofcuriosities.games

# Enable or disable heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Top"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  dica:
    title: Dica
    color: purple
  tip:
    title: Tip
    color: purple
  warning:
    title: Warning
    color: red
  content:
    title: Content Warning
    color: yellow
  conteudo:
    title: Alerta de Conteúdo
    color: yellow

gems:
  - jekyll-pdf

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      pdf: true